type: dropdown
id: workspace
attributes:
  label: Workspace
  options:
    - "Select a workspace..."
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/3scale
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/acr
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/acs
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/adr
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/agent-forge
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/airbrake
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/allure
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/amplication
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/analytics
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/announcements
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/apache-airflow
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/apollo-explorer
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/azure-devops
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/azure-resources
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/azure-sites
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/azure-storage-explorer
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/badges
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/bazaar
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/bitbucket-pull-requests
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/bitrise
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/blackduck
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/bookmarks
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/cicd-statistics
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/cloudbuild
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/code-climate
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/code-coverage
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/codescene
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/confluence
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/copilot
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/cost-insights
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/dynatrace
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/entity-feedback
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/entity-validation
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/explore
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/feedback
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/firehydrant
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/flux
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/fossa
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/gcalendar
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/gcp-projects
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/git-release-manager
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/github-actions
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/github-deployments
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/github-discussions
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/github-issues
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/github-pull-requests-board
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/gitops-profiles
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/gocd
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/grafana
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/graphiql
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/graphql-voyager
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/ilert
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/jaeger
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/jenkins
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/jfrog-artifactory
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/kafka
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/keycloak
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/kiali
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/lighthouse
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/linguist
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/linkerd
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/manage
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/mcp-chat
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/mend
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/microsoft-calendar
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/mta
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/multi-source-security-viewer
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/newrelic
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/nexus-repository-manager
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/nomad
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/npm
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/ocm
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/octopus-deploy
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/opencost
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/periskop
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/pingidentity
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/playlist
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/puppetdb
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/quay
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/rbac
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/redhat-argocd
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/report-portal
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/rollbar
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/scaffolder-backend-module-annotator
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/scaffolder-backend-module-kubernetes
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/scaffolder-backend-module-regex
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/scaffolder-backend-module-servicenow
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/scaffolder-backend-module-sonarqube
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/scaffolder-relation-processor
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/sentry
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/servicenow
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/shortcuts
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/sonarqube
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/splunk
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/stack-overflow
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/stackstorm
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/tech-insights
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/tech-radar
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/tekton
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/todo
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/topology
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/vault
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/wheel-of-names
    - /home/runner/work/backstage-community-plugins/backstage-community-plugins/workspaces/xcmetrics
  default: 0
validations:
  required: true
